Final School website
killy10o10/HTML-CSS-JavaScript-capstone-project pull request #2
Opened 2022-05-20 23:36 UTC by killy10o10

This is a responsive website for a school. Images are added to suit the theme of a kid's school. The teacher section of the home page is generated dynamically in javascript and the mobile screen menu feature is also implemented.

2022-05-21 00:44 UTC, roshan-bajgain requested changes
Hi @killy10o10, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️

- [x]  I cannot see any video recording link about the project either in your PR summary or the readme file. Kindly record video documentation about the project and provide the link either in your PR summary or your readme. 🙏

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 00:44 UTC, roshan-bajgain commented on README.MD
- [x]  Kindly write a brief description of the project in the about section. Currently, users who visit your repo will not have a good picture of what the project is about.

2022-05-21 00:44 UTC, roshan-bajgain commented on README.MD
- [x] There is no live demo so I would suggest you add live demo so any user who visit your repo can see your website easily.

2022-05-21 00:44 UTC, roshan-bajgain commented on README.MD
>  - Inspiration
- [ ] In your README file kindly provide the `Acknowledgement` that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-05-21 00:44 UTC, roshan-bajgain commented on about.html
> +          <li><a href="about.html">About</a></li>
- [ ] There should be possible to navigate between the pages, there's a link from the `Home` page to the `About` page and the opposite too. When I see there is a link for the about page only but when I try to navigate to the `Home page` There is no link so kindly fix it.

2022-05-21 00:44 UTC, roshan-bajgain commented on about.html
> +      </nav>
- [ ] Your design is not like the design provided by microverse. your logo should be aligned a little bit right but it is totally on the left and the `a tag` should have the same color, font size, and font weight. Kindly adjust it
### your design
![his design](https://user-images.githubusercontent.com/81727988/169626753-b381e2fd-ebf0-48f4-86c5-5e661af78463.png)
### Behance design
![figam](https://user-images.githubusercontent.com/81727988/169626773-6eae9e11-feb1-4ce6-9cc3-88d77ceffb19.png)

2022-05-21 00:44 UTC, roshan-bajgain commented on about.html
> +      <div class="logo">
- [ ] Your pages should use the exact same colors, for text, backgrounds, borders, etc, from the original design. So kindly make changes
### your design
![his home](https://user-images.githubusercontent.com/81727988/169627227-7e1177b0-26ba-4bca-bfb9-46148cea38bd.png)
### Behance design
![figma](https://user-images.githubusercontent.com/81727988/169627234-884f8f31-6398-4c30-9702-d9b3292c9ff9.png)

2022-05-21 00:44 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] you are missing this small image beside the image so kindly fix it
### Original design
![hhh](https://user-images.githubusercontent.com/81727988/169627456-c8c43757-5f4d-40bb-8007-c613224f49d5.png)

2022-05-21 21:27 UTC, gtekle requested changes
Hi @killy10o10 :wave: , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![this-close](https://user-images.githubusercontent.com/44057863/169669534-8093869f-bd94-4015-9abf-978156b37243.gif)


# Highlights
:heavy_check_mark: Good use of Github flow
:heavy_check_mark: Meaningful commit messages
:heavy_check_mark: Nice UI design
:heavy_check_mark: Clean code
:heavy_check_mark: No linter errors

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-05-21 21:27 UTC, gtekle commented on about.html
> +      <nav class="desktop-nav">
- [ Optional ] Great, that you have done the changes required by the previous reviewer on the navbar. However, I believe you can still do some improvements to make it look like in the design. 
#### Design
![image](https://user-images.githubusercontent.com/44057863/169668581-341d070e-896b-48b1-9b78-bc40d5a4e938.png)

#### Impl
![image](https://user-images.githubusercontent.com/44057863/169668557-84a4c57a-5645-46e5-804b-cd185c5caa2e.png)

2022-05-21 21:27 UTC, gtekle commented on about.html
> +      <h1 class="intro-heading">LEARN THE PRACTICAL WAY</h1>
- [x] As pointed out by the previous reviewer, one of the project requirements is to stick to the design as much as possible. In this case, the main font color used is #EC5242 with some background color clipping effect. Besided, I believe the text less accessible in its current form. what do you think?
![image](https://user-images.githubusercontent.com/44057863/169668695-e25082f3-be4f-4b81-869e-330de431c323.png)
#### Design
![image](https://user-images.githubusercontent.com/44057863/169668765-20bc094a-1bf4-45c4-961c-f6ad74bc5390.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/169668741-efad3567-8ae2-44cd-9c53-250103053b45.png)

2022-05-21 21:27 UTC, gtekle commented on about.html
> +    </section>
- [ Optional ] Well done on the cool animation effect in the `Register your child` button. And can we add the hover effect on the program card (Stats card in your case) by adding an `outline` as in the Design?
#### Design
![image](https://user-images.githubusercontent.com/44057863/169668914-5b3b435f-04ce-4c20-a8c3-fda115e6a5ad.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/169668890-fdebb5de-c4e5-4594-b534-ec726abd4d8f.png)

2022-05-21 21:27 UTC, gtekle commented on index.html
> +      </button>
- [ Optional ] In the design, the `More` button in the mobile version was supposed to render more Teachers when clicked. By default it renders only two speakers(teachers in your case). What do you think implementing the JavaScript logic to make the button functional. You may also add `Less` to collapse it back to two teachers.
![image](https://user-images.githubusercontent.com/44057863/169669069-c29b02d9-ec35-47c3-b193-63c64f0a275b.png)

2022-05-21 21:27 UTC, gtekle commented on main.js
> +const hamburger = document.getElementById('hamburger');
- [ Optional] I really like the nice mobile nav you created. However, could you make it cover the whole screen and stop the body from scrolling?
![image](https://user-images.githubusercontent.com/44057863/169669149-c25a2855-513e-44f6-af08-a573c5b780e0.png)

2022-05-21 21:27 UTC, gtekle commented on about.html
> +    <footer id="footer">
- [ Optional ]  The footer in the desktop version about page has the logo on the left column and the description text on the right in one row.
#### Design
![image](https://user-images.githubusercontent.com/44057863/169669235-c1d0c802-2622-4fb0-8845-6e3441b6b6f6.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/169669226-90967c7a-0e9c-4cbf-bde7-63eaa2fa78a0.png)

- [ Optional ] In mobile version the layout remains the same as the desktop, but the background color become `white`. And the partner's sectoin becomes visible as well.
#### Footer About page - Mobile
![image](https://user-images.githubusercontent.com/44057863/169669314-417460a3-befd-4551-9851-7bc64632ad76.png)

2022-05-21 21:27 UTC, gtekle commented on README.MD
> +- Cindy Shin: [@adgio07](https://www.behance.net/adagio07)
- [ ] It is good that you acknowledged the Cindy. However, you can use `Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07)` instead to indicate that the original design idea is by Cindy.
![image](https://user-images.githubusercontent.com/44057863/169669504-01b0daa0-3e12-47b4-a0e8-48e0e4877242.png)
#### Appropriate attribution
![image](https://user-images.githubusercontent.com/44057863/169669495-f929f22c-086c-4e0a-9b70-0f93bc636aa1.png)

2022-05-21 23:51 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @killy10o10   , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Decriptive readme file.
:heavy_check_mark: Well implemented design.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-25 01:15 UTC, mahbubul14 requested changes
Hi @killy10o10 ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Good Readme.
:heavy_check_mark: Clean code.

### Optional suggestions

- [ ] Kindly check the inline comments under the review. :arrow_down: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-25 01:15 UTC, mahbubul14 commented on README.MD
- [x] Your video presentation is excellent but you missed adding "a highlight about a piece of the code the student finds interesting or is proud of making". Kindly add that part to your video. :+1:

2022-05-25 01:15 UTC, mahbubul14 commented on about.html
> +    <footer id="footer">
- [ ] In the footer, it should contain a logo aligned to the left and text aligned to the right. Kindly check the following design and work on it for the homepage and the about page both. :+1: 

**Note:** 
- [ ] For the mobile version, the "About page footer background will be white not dark" :+1: 

Your design for Hompage |  Your design for about page
:-------------------------:|:-------------------------:
![f1](https://user-images.githubusercontent.com/70483835/170151577-7e296f44-46cc-4231-90e1-1bd72da43e3f.png) | ![f3](https://user-images.githubusercontent.com/70483835/170150991-f036a6d2-d956-42bc-97f8-f00c6854d3bd.png)

Required design for Hompage |  Required design for about page
:-------------------------:|:-------------------------:
![f2](https://user-images.githubusercontent.com/70483835/170150433-6fbe7085-4eb2-4719-b387-0ec38a0561b3.png) | ![f4](https://user-images.githubusercontent.com/70483835/170151157-e6813dab-ab26-4d7f-b89d-d9ddb4ece898.png)

2022-05-25 01:15 UTC, mahbubul14 commented on index.html
> +      <h1 class="intro-heading">KILLY INTERNATIONAL</h1>
- [ ] It is better for your page to have just one h1 tag, this makes your website semantic and easily readable by browsers. :+1: 

- [ ] I think you should add a small line of text on the top of the page title. :+1: 

Your Implementation  | Design
:-------------------------:|:-------------------------:
![h2](https://user-images.githubusercontent.com/70483835/170153327-dcb369f2-3519-46ac-98d1-c26972e6aea1.png) | ![h1](https://user-images.githubusercontent.com/70483835/170153323-f25858a3-438f-44d8-8cec-c3e3333964a6.png)

2022-05-25 01:15 UTC, mahbubul14 commented on about.html
> +    <footer id="footer">
- [ ] The partner section is missing from the about page. Kindly make it visible on the about us page.

Your Implementation             |  Design
:-------------------------:|:-------------------------:
![p1](https://user-images.githubusercontent.com/70483835/170155068-4e0f6578-5c98-4871-82d4-5ffb959fb729.png) | ![p2](https://user-images.githubusercontent.com/70483835/170155072-88ebfde8-a9b0-489a-8296-fb497f2a539c.png)

2022-05-25 01:15 UTC, mahbubul14 commented on index.html
> +      </button>
- [ ] The "more button" should be increased in size and try to match the design.

Your implementation   |  Design
:-------------------------:|:-------------------------:
![m1](https://user-images.githubusercontent.com/70483835/170156078-8ab464f0-1f51-4bb3-afb6-c8fd739749af.png) | ![m2](https://user-images.githubusercontent.com/70483835/170156515-6146de1e-0b96-42dc-9fad-bb23a4097bdf.png)

- [ ] **[ Optional ]** In the design, the More button in the mobile version was supposed to render more Teachers when clicked. By default, it renders only two speakers(teachers in your case). What do you think about implementing the JavaScript logic to make the button functional? You may also add Less to collapse it back to two teachers.

2022-05-25 01:15 UTC, mahbubul14 commented on styles/button.scss
> +  }
- [ ] Kindly remove the inline comment from your code. The old pieces of code as inline comments make your project look messy. If you need to review a previous version of your code, you can always use git history.

2022-05-25 01:15 UTC, mahbubul14 commented on styles/button.scss
> +  }
- [ ] Kindly remove the inline comment from your code. The old pieces of code as inline comments make your project look messy. If you need to review a previous version of your code, you can always use git history.

2022-05-25 01:15 UTC, mahbubul14 commented on styles/style.css
> +  grid-template-columns: repeat(3, auto); */
- [ ] Kindly remove the inline comments from your code. The old pieces of code as inline comments make your project look messy. If you need to review a previous version of your code, you can always use git history.

2022-05-25 01:15 UTC, mahbubul14 commented on styles/style.css
> +}
- [ ] Kindly remove the inline comment from your code. The old pieces of code as inline comments make your project look messy. If you need to review a previous version of your code, you can always use git history.

2022-05-26 00:27 UTC, killy10o10 commented on README.MD
Thanks for the review. But I did highlight the special feature in my video which is the bubbly button I implemented to suit the theme of a kid school.

2022-05-26 00:33 UTC, MahmoudBakr23 reviewed
Hi @killy10o10 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done working on the required changes from the previous review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 01:22 UTC, merged